// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "plcrashreporter",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "plcrashreporter",
            targets: ["plcrashreporter"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "plcrashreporter",
            dependencies: [],
            path: "Sources",
            exclude: [
                "dwarf_opstream.hpp",
                "dwarf_stack.hpp",
                "PLCrashAsyncDwarfCFAState.hpp",
                "PLCrashAsyncDwarfCIE.hpp",
                "PLCrashAsyncDwarfEncoding.hpp",
                "PLCrashAsyncDwarfExpression.hpp",
                "PLCrashAsyncDwarfFDE.hpp",
                "PLCrashAsyncDwarfPrimitives.hpp",
                "PLCrashAsyncLinkedList.hpp",
                "Autogenerated/PLCrashReport.proto"
            ],
            cSettings: [
                .define("NS_BLOCK_ASSERTIONS", to: "1", .when(configuration: .release)),
                            .define("PLCR_PRIVATE"),
                            .define("PLCF_RELEASE_BUILD"),
                            .define("PLCRASHREPORTER_PREFIX", to: ""),
                            .define("SWIFT_PACKAGE"), // Should be defined by default, Xcode 11.1 workaround.
                            .headerSearchPath("Dependencies/protobuf-c")
                        ],
                        linkerSettings: [
                            .linkedFramework("Foundation")
                        ])
    ]
)
