name: Backtrace-PLCrashReporter
options:
  bundleIdPrefix: io.backtrace.plcrashreporter
targets:
  CrashReporter-macOS:
    templates: 
      - CrashReporter
    templateAttributes:
      platform: macOS
  CrashReporter-iOS:
    templates: 
      - CrashReporter
    templateAttributes:
      platform: iOS
  CrashReporter-tvOS:
    templates: 
      - CrashReporter
    templateAttributes:
      platform: tvOS
      
targetTemplates:
  CrashReporter:
    type: framework
    info:
      path: Resources/Info.plist
    platform: ${platform}
    sources: 
      - path: Source
        includes: 
          - include
        headerVisibility: public
      - path: Source
        exludes: 
          - include
        headerVisibility: project
      - path: Dependencies/protobuf-c/protobuf-c
        includes:
          - protobuf-c.[ch]
        headerVisibility: project
    settings:
      base:
        HEADER_SEARCH_PATHS: "$(SRCROOT)/Dependencies/protobuf-c/protobuf-c"
        GCC_PREFIX_HEADER: "$(SRCROOT)/Source/include/PLCrashNamespace.h"
        PRODUCT_MODULE_NAME: "Backtrace_PLCrashReporter"
        PRODUCT_NAME: "Backtrace_PLCrashReporter"
        CLANG_CXX_LANGUAGE_STANDARD: "c++0x"
        CLANG_CXX_LIBRARY: "libc++"
        PL_MIN_MACOSX_SDK: 101400
        PROTOBUF_C_UNPACK_ERROR: PLCF_DEBUG
        CLANG_ENABLE_OBJC_ARC: NO
      configs:
        debug:
          GCC_PREPROCESSOR_DEFINITIONS: ["$(inherited)", "PLCR_PRIVATE", "PLCF_DEBUG_BUILD", "PLCF_MIN_MACOSX_SDK=$(PL_MIN_MACOSX_SDK)"]
          PL_BUILD_CONFIG_FLAG: PLCF_DEBUG_BUILD
        release:
          GCC_PREPROCESSOR_DEFINITIONS: ["$(inherited)", "PLCR_PRIVATE", "PLCF_RELEASE_BUILD", "PLCF_MIN_MACOSX_SDK=$(PL_MIN_MACOSX_SDK)"]
          PL_BUILD_CONFIG_FLAG: PLCF_RELEASE_BUILD